### ISSUE TITLE
data.archive_file does not support resource tainting

### ISSUE THREAD

**Issue by tbobm** [hashicorp/terraform-provider-archive#122]
It seems like `archive_file` datasource does not support tainting at the moment, is this a bug or is it not supposed to support tainting ?

### Terraform Version

```console
$ terraform -v
Terraform v1.1.2
on linux_amd64
+ provider registry.terraform.io/hashicorp/archive v2.2.0
```

### Affected Resource(s)

- data.archive_file

If this issue appears to affect multiple resources, it may be an issue with Terraform's core, so please mention this.

### Terraform Configuration Files
```hcl
data "archive_file" "test" {
  type = "zip"
  source_file = "${path.module}/test.json"
  output_path = "${path.module}/out.zip"
}

output "path" {
  value = data.archive_file.test.output_path
}

output "md5" {
  value = data.archive_file.test.output_md5
}
```

### Debug Output

https://gist.github.com/tbobm/653cb4b2b3b057da8fcbc025e02a454b

### Expected Behavior

Upon tainting the archive_file, I expect it to be registered as tainted in order to manually force recreation during the next `terraform apply`

### Actual Behavior

The resource does not seem to support tainting.

### Steps to Reproduce
Please list the steps required to reproduce the issue, for example:
1. `terraform taint data.archive_file.test`

**Comment by bflad** [comment]
Hi @tbobm 👋  Thank you for raising this and sorry you ran into trouble here.

By design, tainting in Terraform only applies to managed resources (e.g. configurations like `resource "example_thing" "example" {...}`) to trigger deletion and recreation. Data sources (e.g. configurations like `data "example_thing" "example" {...}`) on the other hand are automatically refreshed every Terraform run, so in effect, they are "tainted" every run.

If you have further configuration or troubleshooting questions, please also check out [HashiCorp Discuss](https://discuss.hashicorp.com/) where there are far more folks watching these types of topics and able to answer. The issues in this repository are only monitored by a small subset of provider maintainers for bug reports and feature requests.
