### ISSUE TITLE
Error installing provider "archive": openpgp: signature made by unknown entity.

### ISSUE THREAD

**Issue by sineadie** [hashicorp/terraform-provider-archive#97]
### Terraform Version
0.11.14

### Affected Resource
- archive_file

### Terraform Configuration Files
```
data "archive_file" "lambda_audit_zip" {
  type        = "zip"
  source_dir  = "${path.module}/source"
  output_path = "${path.module}/audit.zip"
}
```

### Expected Behavior
What should have happened? 
Terraform init/plan runs with no issues. 

### Actual Behavior
What actually happened?
Terraform init command is failing with:
```
Error installing provider "archive": openpgp: signature made by unknown entity.

Terraform analyses the configuration and state and automatically downloads plugins for the providers used. However, when attempting to download this plugin an unexpected error occured.
This may be caused if for some reason Terraform is unable to reach the plugin repository. The repository may be unreachable if access is blocked by a firewall.
If automatic installation is not possible or desirable in your environment, you may alternatively manually install plugins by downloading a suitable distribution package and placing the plugin's executable file in the following directory:
      terraform.d/plugins/linux_amd64
```

### Steps to Reproduce
1. `terraform init`

It looks like this provider was updated a few hours ago, and since then we are seeing this issue which is causing our builds to fail:
https://registry.terraform.io/providers/hashicorp/archive/latest

**Comment by bflad** [comment]
Hi @sineadie 👋  Thank you for reporting this and sorry you ran into trouble here.

The short answer here is that upgrading to the latest version of this provider (and future released versions of HashiCorp providers) requires upgrading to Terraform CLI version 0.11.15 due to a security event. Otherwise, you will need to pin the provider version using a Terraform 0.11 configuration such as:

```terraform
provider "archive" {
  version = "2.1.0"
}
```

Please see the full writeup at [HCSEC-2021-12 - Codecov Security Event and HashiCorp GPG Key Exposure](https://discuss.hashicorp.com/t/hcsec-2021-12-codecov-security-event-and-hashicorp-gpg-key-exposure/23512) and [Terraform Updates for HCSEC-2021-12](https://discuss.hashicorp.com/t/terraform-updates-for-hcsec-2021-12/23570) for more details.

**Comment by sineadie** [comment]
Hey @bflad

Thanks for your response, however, I've been unable to use any earlier version of Terraform 0.11.15 with the archive provider no matter what version of the provider I pin. Any ideas why?
